version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - certbot
    networks:
      - web_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "aws-0-us-east-2.pooler.supabase.com:155.138.151.119"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - web_network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@solforge.live --agree-tos --no-eff-email -d solforge.live -d www.solforge.live
    networks:
      - web_network

volumes:
  static_volume:
  media_volume:
  certbot_data:
  certbot_www:

networks:
  web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 